# -*- coding: utf-8 -*-
"""CIE1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14q65R0bZEVuqN-Jbz3e2TmhcoE2x51xY
"""

import pandas as pd
data={'product_name':['Tv','mens_weaar','sofa','pan'],
      'category':['electronics','clothing','home','kitchen'],
      'price':['45000','1700','15000','600'],
      'quntity_sold':['5','10','5','12']}
df=pd.DataFrame(data)
print(df)

pd.pivot_table(df, values='price', aggfunc='mean',index='category',)

pd.pivot_table(df, values=['price','quntity_sold'], aggfunc=['sum'],index='category')

import pandas as pd
data=pd.read_csv('mtcars.csv')
data

import matplotlib.pyplot as plt
plt.hist(data['mpg'],edgecolor='k')
plt.xlabel('MPG')
plt.ylabel('Frequency')
plt.show()

plt.scatter(data['wt'],data['mpg'],marker='*')
plt.xlabel('weight')
plt.ylabel('mpg')
plt.title('Scatter plot')
plt.show

trans=data['am'].value_counts()
trans.plot(kind='bar',edgecolor='k')
plt.title('freQuency distribution of transmission type cars')
plt.xlabel('transmission')
plt.ylabel('frequency')
plt.show()

plt.boxplot(data['mpg'],patch_artist=True)
plt.xlabel('mpg')
plt.show()