# -*- coding: utf-8 -*-
"""CIE2org.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qO0mpEnaeTigqAHsMyhZgDXFmi4YtOwo
"""

import pandas as pd
df=pd.read_csv("titanic.csv")
df

df.describe()

df.info()

df.head()

df.duplicated().sum()

m1=df["Age"].mean()
m1

m2=df["Age"].mode()
m2

m3=df["Age"].median()
m3

import pandas as pd

titanic_data=pd.read_csv("titanic.csv")

null_age=titanic_data["Age"].isnull().sum()
null_fare=titanic_data["Fare"].isnull().sum()

mean_age=titanic_data["Age"].mean()
mean_fare=titanic_data["Fare"].mean()

titanic_data['Age'].fillna(titanic_data["Age"].mean(),inplace=True)
titanic_data["Fare"].fillna(titanic_data["Fare"].mean(),inplace=True)


null_age_after=titanic_data["Age"].isnull().sum()
null_fare_after=titanic_data["Fare"].isnull().sum()

print("null values in before age",{null_age})

print("null values in before fare",{null_fare})

print("null values in before age",{null_age_after})

print("null values in before fare",{null_fare_after})

titanic_data.isnull().sum()

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
df=pd.read_csv("titanic.csv")
from scipy import stats
z_scores=np.abs(stats.zscore(df['Fare']))
threshold=3
outliers=df['Fare'][z_scores > threshold]
sns.boxplot(df['Fare'],color='blue')
plt.title('boxplot of fare colum')
plt.xlabel('Fare')
plt.show()
print(outliers)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("titanic.csv")
df['Survived'].replace({0:'not Survived',1:'Survived'}, inplace=True)
survived_counts=df['Survived'].value_counts()
print(survived_counts)
sns.countplot(x='Survived',hue='Pclass',data=df)
plt.show()