# -*- coding: utf-8 -*-
"""CIE3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AlzpZg1NO8tq83vHq9rLMDm6r32H5Eu1
"""

import pandas as pd
df=pd.read_csv('Housing.csv')
df

# @title EDA

df.info

df.describe

df.head

df.duplicated().sum()

df['AGE'].unique()

# @title preprocessing the data

A=df['AGE'].isnull().sum()
B=df['CHAS'].isnull().sum()
m1=df['AGE'].mean()
m2=df['CHAS'].mean()
df['AGE'].fillna(m1,inplace=True)
df['CHAS'].fillna(m2,inplace=True)
c=df['AGE'].isnull().sum()
d=df['CHAS'].isnull().sum()
print("Before age",A)
print("After age",c)
print("Before chas",B)
print("After chas",d)

# @title Spliting
from sklearn.model_selection import train_test_split
x=df['AGE']
y=df['CHAS']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_test)
print(x_train)
print(y_test)
print(y_train)

# @title iris data set

# @title importing libaries

import pandas as pd

# @title loadin dataset
iris=pd.read_csv('Iris.csv')
iris

iris.head()

iris.describe()

iris.info()

A=iris['SepalLengthCm'].isnull().sum()
b=iris['PetalLengthCm'].isnull().sum()
print("null values in SepalLengthCm",A)
print("null values in PetalLengthCm",b)

#@title spliting
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
from sklearn.linear_model import LinearRegression

iris=load_iris()
iris

x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
print(r2)
print(mae)
print(mse)